import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </Providers>
    </html>
  );
}
